// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsLP7VffqEjyk1mG-tSk7-d8qU3Xj4qTk',
    appId: '1:512664442817:web:e7b7738214c6d847e84140',
    messagingSenderId: '512664442817',
    projectId: 'my-phone-cb8ea',
    authDomain: 'my-phone-cb8ea.firebaseapp.com',
    storageBucket: 'my-phone-cb8ea.firebasestorage.app',
    measurementId: 'G-V97ZG3EYHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAbOxxiI3XfM31pWPIN6q0aRchcGi0MY',
    appId: '1:512664442817:android:75565750f3deda34e84140',
    messagingSenderId: '512664442817',
    projectId: 'my-phone-cb8ea',
    storageBucket: 'my-phone-cb8ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3zxJxrzu-hQ1_elsQ-HuB1WsB3mbbd-M',
    appId: '1:512664442817:ios:19cb25866f690620e84140',
    messagingSenderId: '512664442817',
    projectId: 'my-phone-cb8ea',
    storageBucket: 'my-phone-cb8ea.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppFrutes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3zxJxrzu-hQ1_elsQ-HuB1WsB3mbbd-M',
    appId: '1:512664442817:ios:19cb25866f690620e84140',
    messagingSenderId: '512664442817',
    projectId: 'my-phone-cb8ea',
    storageBucket: 'my-phone-cb8ea.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppFrutes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsLP7VffqEjyk1mG-tSk7-d8qU3Xj4qTk',
    appId: '1:512664442817:web:26f5b374b86453c5e84140',
    messagingSenderId: '512664442817',
    projectId: 'my-phone-cb8ea',
    authDomain: 'my-phone-cb8ea.firebaseapp.com',
    storageBucket: 'my-phone-cb8ea.firebasestorage.app',
    measurementId: 'G-MLNM268M76',
  );
}
