// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARaurv0bc5uJtLqN1NLReQ-gt0u6PXj24',
    appId: '1:542163824579:web:a38a5177ee2880bba45776',
    messagingSenderId: '542163824579',
    projectId: 'frut-hub-e8eaa',
    authDomain: 'frut-hub-e8eaa.firebaseapp.com',
    storageBucket: 'frut-hub-e8eaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsVmk3BbPPoihb6j9G8pGBJjg2PW8N2UM',
    appId: '1:542163824579:android:0f9f33b79497e001a45776',
    messagingSenderId: '542163824579',
    projectId: 'frut-hub-e8eaa',
    storageBucket: 'frut-hub-e8eaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB37uXFWs-AMad69Z5V9f6GoPNwRUG8rcw',
    appId: '1:542163824579:ios:a31d669290977cb9a45776',
    messagingSenderId: '542163824579',
    projectId: 'frut-hub-e8eaa',
    storageBucket: 'frut-hub-e8eaa.firebasestorage.app',
    iosClientId: '542163824579-snfn8bsf4bg2urnvp628fv9frc56ublm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAppFrutes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB37uXFWs-AMad69Z5V9f6GoPNwRUG8rcw',
    appId: '1:542163824579:ios:a31d669290977cb9a45776',
    messagingSenderId: '542163824579',
    projectId: 'frut-hub-e8eaa',
    storageBucket: 'frut-hub-e8eaa.firebasestorage.app',
    iosClientId: '542163824579-snfn8bsf4bg2urnvp628fv9frc56ublm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAppFrutes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARaurv0bc5uJtLqN1NLReQ-gt0u6PXj24',
    appId: '1:542163824579:web:29de0abf9b031460a45776',
    messagingSenderId: '542163824579',
    projectId: 'frut-hub-e8eaa',
    authDomain: 'frut-hub-e8eaa.firebaseapp.com',
    storageBucket: 'frut-hub-e8eaa.firebasestorage.app',
  );
}
